version: "3.9"

x-common-env: &common-env
  Jwt__Secret: "CHANGE_ME_super_secret_key_min_32_chars_long_12345"
  Jwt__Issuer: "microservices-auth"
  Jwt__Audience: "microservices-clients"
  Jwt__ExpiryMinutes: "60"
  InternalApi__ApiKey: "CHANGE_ME_internal_service_key_67890"
  ASPNETCORE_ENVIRONMENT: "Development"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms_sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools18
    container_name: ms_sqlserver_init
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./Database:/scripts
    entrypoint: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong!Passw0rd' -C -i /scripts/auth_db.sql &&
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong!Passw0rd' -C -i /scripts/inventory_db.sql &&
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong!Passw0rd' -C -i /scripts/order_db.sql
      "

  auth-service:
    build:
      context: .
      dockerfile: src/AuthService/Dockerfile
    container_name: auth_service
    restart: unless-stopped
    depends_on:
      sqlserver-init:
        condition: service_completed_successfully
    environment:
      <<: *common-env
      ConnectionStrings__AuthDb: "Server=sqlserver,1433;Database=auth_db;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "5001:8080"

  inventory-service:
    build:
      context: .
      dockerfile: src/InventoryService/Dockerfile
    container_name: inventory_service
    restart: unless-stopped
    depends_on:
      sqlserver-init:
        condition: service_completed_successfully
    environment:
      <<: *common-env
      ConnectionStrings__InventoryDb: "Server=sqlserver,1433;Database=inventory_db;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "5002:8080"

  order-service:
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    container_name: order_service
    restart: unless-stopped
    depends_on:
      sqlserver-init:
        condition: service_completed_successfully
      inventory-service:
        condition: service_started
    environment:
      <<: *common-env
      ConnectionStrings__OrderDb: "Server=sqlserver,1433;Database=order_db;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      InventoryService__BaseUrl: "http://inventory-service:8080"
    ports:
      - "5003:8080"

volumes:
  sqldata:
